// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://schuyrbqprqkdwrrjppj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjaHV5cmJxcHJxa2R3cnJqcHBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyOTYxMzAsImV4cCI6MjA2Nzg3MjEzMH0.3qy0R9vRp8ZaARyuq-UBXEI5rSVh53sz8ci7NGCrXBc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});